import 'dart:async';

import 'package:chatview_utils/chatview_utils.dart';
import 'package:flutter/foundation.dart';

import '../enum.dart';
import '../models/chat_room.dart';
import '../models/chat_room_display_metadata.dart';
import '../models/chat_room_metadata.dart';
import '../models/chat_room_participant.dart';
import '../models/config/message_ops_config.dart';
import '../models/message_dm.dart';
import '../typedefs.dart';

/// Defined different methods to interact with a cloud database.
abstract interface class DatabaseService {
  const DatabaseService._();

  /// Asynchronously fetches messages and returns [List] of [MessageDm].
  Future<List<MessageDm>> getMessages({
    required int retry,
    required String chatId,
    required MessageSortBy sortBy,
    required MessageSortOrder sortOrder,
    int? limit,
    dynamic startAfterDocument,
  });

  /// Retrieves a stream of message batches from database with
  /// document snapshot.
  Stream<List<MessageDm>> getMessagesStreamWithSnapshot({
    required String chatId,
    required MessageSortBy sortBy,
    required MessageSortOrder sortOrder,
    int? limit,
    dynamic startAfterDocument,
    DateTime? from,
  });

  /// Retrieves a stream of message batches from database.
  Stream<List<Message>> getMessagesStream({
    required String chatId,
    required MessageSortBy sortBy,
    required MessageSortOrder sortOrder,
    int? limit,
    dynamic startAfterDocument,
    DateTime? from,
  });

  /// Retrieves a stream of users batches from database.
  Stream<List<ChatUser>> getUsersStream({int? limit});

  /// Retrieves a list of users batches from database.
  Future<List<ChatUser>> getUsers({required int retry, int? limit});

  /// Retrieves a stream of a particular user based on the provided user ID.
  Stream<ChatUser?> getUserStreamById(String userId);

  /// Retrieves a stream of chat room users batches from the database.
  Stream<List<ChatRoomParticipant>> getChatRoomParticipantsStream({
    required String userId,
    required String chatId,
    int? limit,
  });

  /// Returns a stream of chat room users (excluding the current user)
  /// from the database.
  Stream<Map<String, ChatRoomParticipant>> getChatRoomUsersMetadataStream({
    required String chatId,
    required String userId,
    required bool observeUserInfoChanges,
    int? limit,
  });

  /// Retrieves a stream of unread messages count for the given chat room.
  Stream<int> getUnreadMessagesCount({
    required String chatId,
    required String userId,
    DateTime? from,
  });

  /// Retrieves the current user and a list of users in the chat room from the
  /// database.
  Future<ChatRoomMetadata?> getChatRoomMetadata({
    required int retry,
    required String chatId,
    required String userId,
  });

  /// Retrieves a stream of messages along with their associated operation
  /// types.
  Stream<Map<Message, DocumentType>> getMessagesStreamWithOperationType({
    required String chatId,
    required MessageSortBy sortBy,
    required MessageSortOrder sortOrder,
    int? limit,
  });

  /// Asynchronously adds a new message and returns nullable [Message].
  Future<Message?> addMessage({
    required int retry,
    required String chatId,
    required Message message,
    required bool useAutoGeneratedId,
    required MessageOpsConfig messageOpsConfig,
  });

  /// Asynchronously delete a message and returns [bool] value.
  Future<bool> deleteMessage({
    required int retry,
    required String chatId,
    required Message message,
    required MessageOpsConfig messageConfig,
  });

  /// Asynchronously update a message.
  Future<void> updateMessage({
    required int retry,
    required String userId,
    required String chatId,
    required Message message,
    MessageStatus? status,
    ReactionCallback? reaction,
  });

  /// Updates the chat room user with the provided typing status, or
  /// membership status.
  Future<void> updateChatRoomUserMetadata({
    required int retry,
    required String chatId,
    required String userId,
    TypeWriterStatus? typingStatus,
    MembershipStatus? membershipStatus,
    PinStatus? pinStatus,
    MuteStatus? muteStatus,
    Map<String, dynamic>? chatRoomUserData,
    ValueGetter<ChatRoomParticipant>? ifDataNotFound,
  });

  /// Updates the current user document with the current user status.
  Future<bool> updateUserActiveStatus({
    required int retry,
    required String userId,
    required UserActiveStatus userStatus,
  });

  /// Returns a stream of [ChatRoom]s
  Stream<List<ChatRoom>> getChatsStream({
    required String userId,
    required ChatSortBy sortBy,
    required bool includeEmptyChats,
    required bool includeUnreadMessagesCount,
    int? limit,
  });

  /// Returns a stream of [ChatRoom] changes
  Stream<ChatRoom?> chatRoomChangesStream({
    required String userId,
    required bool includeEmptyChats,
    required bool includeUnreadMessagesCount,
    required ValueSetter<String>? onRemovedChat,
    int? limit,
  });

  /// Creates a one-to-one chat
  Future<String?> createOneToOneChat({
    required String userId,
    required String otherUserId,
    String? chatRoomId,
  });

  /// Creates a new group chat
  Future<String?> createGroupChat({
    required String userId,
    required String groupName,
    required Map<String, Role> participants,
    String? groupProfilePic,
    String? chatRoomId,
  });

  /// Updates an existing group chat.
  Future<bool> updateGroupChat({
    required int retry,
    required String chatId,
    String? groupName,
    String? groupProfilePic,
  });

  /// Adds a user to the group chat
  Future<bool> addUserInGroup({
    required int retry,
    required String chatId,
    required String userId,
    required Role role,
    required bool includeAllChatHistory,
    DateTime? startDate,
  });

  /// Removes a user from the group chat
  Future<bool> removeUserFromGroup({
    required int retry,
    required String chatId,
    required String userId,
    required String removeUserId,
    required bool deleteGroupIfSingleUser,
    required DeleteChatMediaCallback deleteChatMedia,
  });

  /// Retrieves a stream of [ChatRoomDisplayMetadata]
  Stream<ChatRoomDisplayMetadata> getGroupChatDisplayMetadataStream(
    String chatId,
  );

  /// Checks if a one-to-one chat exists
  Future<String?> findOneToOneChatRoom({
    required int retry,
    required String userId,
    required String otherUserId,
  });

  /// Returns a real-time stream of metadata for a specific chat room.
  Stream<ChatRoomDisplayMetadata> getChatRoomDisplayMetadataStream({
    required ChatRoomType chatRoomType,
    required String chatId,
    String? userId,
  });

  /// Retrieves the timestamp of when a user was added to a group chat.
  Future<DateTime?> getUserMembershipTimestamp({
    required int retry,
    required String chatId,
    required String userId,
  });

  /// Deletes the entire chat
  Future<bool> deleteChat({
    required int retry,
    required String chatId,
    DeleteChatMediaCallback? deleteMedia,
  });

  /// Retrieves a list of messages surrounding a specific message in a chat.
  Future<List<Message>> getSurroundingMessages({
    required String chatId,
    required int retry,
    required String messageId,
    required int batchSize,
    required MessageSortBy sortBy,
    required MessageSortOrder sortOrder,
  });

  /// Retrieves a list of previous messages in a chat room.
  Future<List<Message>> getPreviousMessages({
    required String chatId,
    required int retry,
    required String messageId,
    required int batchSize,
  });

  /// Retrieves a list of next messages in a chat room.
  Future<List<Message>> getNextMessages({
    required String chatId,
    required int retry,
    required String messageId,
    required int batchSize,
  });
}
